### ISSUE TITLE
Call from invalid thread

### ISSUE THREAD

**Issue by boexler** [AvaloniaCommunity/Material.Avalonia#117]
I have imported your SnackBar into my application and when hovering over the menu items, I get the following unhandled exception.

```txt
   at Avalonia.Threading.Dispatcher.VerifyAccess() in /_/src/Avalonia.Base/Threading/Dispatcher.cs:line 49
   at Avalonia.AvaloniaObject.VerifyAccess() in /_/src/Avalonia.Base/AvaloniaObject.cs:line 140
   at Avalonia.AvaloniaObject.GetValue[T](StyledPropertyBase`1 property) in /_/src/Avalonia.Base/AvaloniaObject.cs:line 254
   at Avalonia.Animation.Animatable.get_Clock() in /_/src/Avalonia.Animation/Animatable.cs:line 37
   at Avalonia.Animation.Animators.Animator`1.Run(Animation animation, Animatable control, IClock clock, Action onComplete) in /_/src/Avalonia.Animation/Animators/Animator`1.cs:line 117
   at Avalonia.Animation.DisposeAnimationInstanceSubject`1.System.IObserver<System.Boolean>.OnNext(Boolean matchVal) in /_/src/Avalonia.Animation/DisposeAnimationInstanceSubject.cs:line 50
   at System.Reactive.Subjects.Subject`1.OnNext(T value) in /_/Rx.NET/Source/src/System.Reactive/Subjects/Subject.cs:line 147
   at Material.Styles.Additional.Animations.ReverseAfterEndAnimation.<>c__DisplayClass8_0.<<Apply>b__0>d.MoveNext()
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Threading.Tasks.Task.<>c.<ThrowAsync>b__139_1(Object state)
   at System.Threading.QueueUserWorkItemCallbackDefaultContext.Execute()
   at System.Threading.ThreadPoolWorkQueue.Dispatch()
   at System.Threading._ThreadPoolWaitCallback.PerformWaitCallback()
```

**Comment by appleneko2001** [comment]
And another thing is ... This issue doesn't related with `SnackBar`! 😅
