### ISSUE TITLE
Error after migrating to Avalonia 0.10.11: RunAsync in ControllableAnimationBase does not have an implementation

### ISSUE THREAD

**Issue by ctrl-alt-d** [AvaloniaCommunity/Material.Avalonia#133]
After migrating to Avalonia 0.10.11 I get this error **running** the app on Mac OS X (M1) :

>System.TypeLoadException: Method 'RunAsync' in type 'Material.Styles.Additional.Animations.ControllableAnimationBase' from assembly 'Material.Styles, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null' does not have an implementation.
>   at CompiledAvaloniaXaml.!AvaloniaResources.Populate:/ToggleSwitch.xaml(IServiceProvider , Styles )
>   at CompiledAvaloniaXaml.!AvaloniaResources.Build:/ToggleSwitch.xaml(IServiceProvider )
>   at CompiledAvaloniaXaml.!XamlLoader.TryLoad(String )

Check the source code at this branch: https://github.com/ctrl-alt-d/eaprecull/tree/migratingTo250 (just clone, change branch and run)

I'm looking for a bit of help to fix the issue. **Thanks a lot** (I moved to Avalonia 0.10.11 [to be able to execute app on MAC OS X M1](https://github.com/AvaloniaUI/Avalonia/discussions/7233))

Full trace error:

```console
Unhandled exception. System.Reflection.TargetInvocationException: Exception has been thrown by the target of an invocation.
 ---> System.Reflection.TargetInvocationException: Exception has been thrown by the target of an invocation.
 ---> System.TypeLoadException: Method 'RunAsync' in type 'Material.Styles.Additional.Animations.ControllableAnimationBase' from assembly 'Material.Styles, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null' does not have an implementation.
   at CompiledAvaloniaXaml.!AvaloniaResources.Populate:/ToggleSwitch.xaml(IServiceProvider , Styles )
   at CompiledAvaloniaXaml.!AvaloniaResources.Build:/ToggleSwitch.xaml(IServiceProvider )
   at CompiledAvaloniaXaml.!XamlLoader.TryLoad(String )
   --- End of inner exception stack trace ---
   at System.RuntimeMethodHandle.InvokeMethod(Object target, Span`1& arguments, Signature sig, Boolean constructor, Boolean wrapExceptions)
   at System.Reflection.RuntimeMethodInfo.Invoke(Object obj, BindingFlags invokeAttr, Binder binder, Object[] parameters, CultureInfo culture)
   at System.Reflection.MethodBase.Invoke(Object obj, Object[] parameters)
   at Avalonia.Markup.Xaml.AvaloniaXamlLoader.Load(Uri uri, Uri baseUri) in /_/src/Markup/Avalonia.Markup.Xaml/AvaloniaXamlLoader.cs:line 57
   at Avalonia.Markup.Xaml.Styling.StyleInclude.get_Loaded() in /_/src/Markup/Avalonia.Markup.Xaml/Styling/StyleInclude.cs:line 54
   at Avalonia.Markup.Xaml.Styling.StyleInclude.TryGetResource(Object key, Object& value) in /_/src/Markup/Avalonia.Markup.Xaml/Styling/StyleInclude.cs:line 89
   at Avalonia.Styling.Styles.TryGetResource(Object key, Object& value) in /_/src/Avalonia.Styling/Styling/Styles.cs:line 163
   at Avalonia.Markup.Xaml.Styling.StyleInclude.TryGetResource(Object key, Object& value) in /_/src/Markup/Avalonia.Markup.Xaml/Styling/StyleInclude.cs:line 91
   at Avalonia.Styling.Styles.TryGetResource(Object key, Object& value) in /_/src/Avalonia.Styling/Styling/Styles.cs:line 163
   at Avalonia.Markup.Xaml.Styling.StyleInclude.TryGetResource(Object key, Object& value) in /_/src/Markup/Avalonia.Markup.Xaml/Styling/StyleInclude.cs:line 91
   at Avalonia.Styling.Styles.TryGetResource(Object key, Object& value) in /_/src/Avalonia.Styling/Styling/Styles.cs:line 163
   at Avalonia.Application.Avalonia.Controls.IResourceNode.TryGetResource(Object key, Object& value) in /_/src/Avalonia.Controls/Application.cs:line 201
   at Avalonia.Markup.Xaml.MarkupExtensions.StaticResourceExtension.ProvideValue(IServiceProvider serviceProvider) in /_/src/Markup/Avalonia.Markup.Xaml/MarkupExtensions/StaticResourceExtension.cs:line 48
   at CompiledAvaloniaXaml.!AvaloniaResources.Populate:/ComboBox.xaml(IServiceProvider , Styles )
   at CompiledAvaloniaXaml.!AvaloniaResources.Build:/ComboBox.xaml(IServiceProvider )
   at CompiledAvaloniaXaml.!XamlLoader.TryLoad(String )
   --- End of inner exception stack trace ---
   at System.RuntimeMethodHandle.InvokeMethod(Object target, Span`1& arguments, Signature sig, Boolean constructor, Boolean wrapExceptions)
   at System.Reflection.RuntimeMethodInfo.Invoke(Object obj, BindingFlags invokeAttr, Binder binder, Object[] parameters, CultureInfo culture)
   at System.Reflection.MethodBase.Invoke(Object obj, Object[] parameters)
   at Avalonia.Markup.Xaml.AvaloniaXamlLoader.Load(Uri uri, Uri baseUri) in /_/src/Markup/Avalonia.Markup.Xaml/AvaloniaXamlLoader.cs:line 57
   at Avalonia.Markup.Xaml.Styling.StyleInclude.get_Loaded() in /_/src/Markup/Avalonia.Markup.Xaml/Styling/StyleInclude.cs:line 54
   at Avalonia.Markup.Xaml.Styling.StyleInclude.Avalonia.Controls.IResourceProvider.AddOwner(IResourceHost owner) in /_/src/Markup/Avalonia.Markup.Xaml/Styling/StyleInclude.cs:line 98
   at Avalonia.Styling.Styles.Avalonia.Controls.IResourceProvider.AddOwner(IResourceHost owner) in /_/src/Avalonia.Styling/Styling/Styles.cs:line 240
   at Avalonia.Markup.Xaml.Styling.StyleInclude.Avalonia.Controls.IResourceProvider.AddOwner(IResourceHost owner) in /_/src/Markup/Avalonia.Markup.Xaml/Styling/StyleInclude.cs:line 98
   at Avalonia.Styling.Styles.Avalonia.Controls.IResourceProvider.AddOwner(IResourceHost owner) in /_/src/Avalonia.Styling/Styling/Styles.cs:line 240
   at Avalonia.Markup.Xaml.Styling.StyleInclude.Avalonia.Controls.IResourceProvider.AddOwner(IResourceHost owner) in /_/src/Markup/Avalonia.Markup.Xaml/Styling/StyleInclude.cs:line 98
   at Avalonia.Styling.Styles.<OnCollectionChanged>g__Add|52_1(IList items) in /_/src/Avalonia.Styling/Styling/Styles.cs:line 287
   at Avalonia.Styling.Styles.OnCollectionChanged(Object sender, NotifyCollectionChangedEventArgs e) in /_/src/Avalonia.Styling/Styling/Styles.cs:line 318
   at Avalonia.Collections.AvaloniaList`1.NotifyAdd(T item, Int32 index) in /_/src/Avalonia.Base/Collections/AvaloniaList.cs:line 681
   at Avalonia.Collections.AvaloniaList`1.Add(T item) in /_/src/Avalonia.Base/Collections/AvaloniaList.cs:line 205
   at Avalonia.Styling.Styles.Add(IStyle item) in /_/src/Avalonia.Styling/Styling/Styles.cs:line 201
   at UI.ER.AvaloniaUI.App.!XamlIlPopulate(IServiceProvider , App ) in /Users/dani/Documents/projectes/eaprecull/UI.ER.AvaloniaUI/App.axaml:line 11
   at UI.ER.AvaloniaUI.App.!XamlIlPopulateTrampoline(App )
   at UI.ER.AvaloniaUI.App.Initialize() in /Users/dani/Documents/projectes/eaprecull/UI.ER.AvaloniaUI/App.axaml.cs:line 14
   at Avalonia.Controls.AppBuilderBase`1.Setup() in /_/src/Avalonia.Controls/AppBuilderBase.cs:line 310
   at Avalonia.Controls.AppBuilderBase`1.SetupWithLifetime(IApplicationLifetime lifetime) in /_/src/Avalonia.Controls/AppBuilderBase.cs:line 179
   at Avalonia.ClassicDesktopStyleApplicationLifetimeExtensions.StartWithClassicDesktopLifetime[T](T builder, String[] args, ShutdownMode shutdownMode) in /_/src/Avalonia.Controls/ApplicationLifetimes/ClassicDesktopStyleApplicationLifetime.cs:line 186
   at UI.ER.AvaloniaUI.Program.Main(String[] args) in /Users/dani/Documents/projectes/eaprecull/UI.ER.AvaloniaUI/Program.cs:line 12
```

**Comment by SKProCH** [comment]
Hello, @ctrl-alt-d 
This bug has been fixed in nightly builds.
Does this solve your problem?

**Comment by Maruhl** [comment]
Yes it works for me.

**Comment by ctrl-alt-d** [comment]
Hello @SKProCH ,

it works like a charm 👏 .   Thanks 

<img width="1841" alt="Captura de pantalla 2021-12-22 a les 8 23 50" src="https://user-images.githubusercontent.com/3105983/147052275-00345fc0-daea-41ad-9f3c-f5cee2949ea6.png">
