### ISSUE TITLE
Unable to get the theme working: TargetInvocationException

### ISSUE THREAD

**Issue by aybe** [AvaloniaCommunity/Material.Avalonia#160]
I am unable to get the theme working with the latest version of Avalonia.

Tried with the example at https://github.com/AvaloniaCommunity/Material.Avalonia:

```
<Application xmlns="https://github.com/avaloniaui"
             xmlns:x="http://schemas.microsoft.com/winfx/2006/xaml"
             xmlns:local="using:PSX.Avalonia"
             xmlns:themes="clr-namespace:Material.Styles.Themes;assembly=Material.Styles"
             x:Class="PSX.Avalonia.App">
    <Application.DataTemplates>
        <local:ViewLocator />
    </Application.DataTemplates>

    <Application.Styles>
        <themes:MaterialTheme BaseTheme="Dark" PrimaryColor="Purple" SecondaryColor="Lime" />
    </Application.Styles>

</Application>
```

```
Severity	Code	Description	Project	File	Line	Suppression State
Error	AXN0002	XamlX.XamlParseException: Unable to resolve type MaterialTheme from namespace clr-namespace:Material.Styles.Themes;assembly=Material.Styles Line 11, position 10.	PSX.Avalonia	C:\Users\aybe\source\repos\ProjectPSX\PSX.Avalonia\CSC	1	
```

Tried with the example at https://github.com/AvaloniaCommunity/Material.Avalonia/wiki/Simple-getting-started:

```
<Application xmlns="https://github.com/avaloniaui"
             xmlns:x="http://schemas.microsoft.com/winfx/2006/xaml"
             xmlns:local="using:PSX.Avalonia"
             xmlns:themes="clr-namespace:Material.Styles.Themes;assembly=Material.Styles"
             x:Class="PSX.Avalonia.App">
    <Application.DataTemplates>
        <local:ViewLocator />
    </Application.DataTemplates>

    <Application.Resources>
        <themes:BundledTheme BaseTheme="Light" PrimaryColor="Teal" SecondaryColor="Amber" />
    </Application.Resources>

    <Application.Styles>
        <StyleInclude Source="avares://Material.Avalonia/Material.Avalonia.Templates.xaml" />
    </Application.Styles>

</Application>
```

```
System.Reflection.TargetInvocationException
  HResult=0x80131604
  Message=Exception has been thrown by the target of an invocation.
  Source=System.Private.CoreLib
  StackTrace:
   at System.RuntimeMethodHandle.InvokeMethod(Object target, Span`1& arguments, Signature sig, Boolean constructor, Boolean wrapExceptions)
   at System.Reflection.RuntimeMethodInfo.Invoke(Object obj, BindingFlags invokeAttr, Binder binder, Object[] parameters, CultureInfo culture)
   at System.Reflection.MethodBase.Invoke(Object obj, Object[] parameters)
   at Avalonia.Markup.Xaml.AvaloniaXamlLoader.Load(Uri uri, Uri baseUri)
   at Avalonia.Markup.Xaml.Styling.StyleInclude.get_Loaded()
   at Avalonia.Markup.Xaml.Styling.StyleInclude.Avalonia.Controls.IResourceProvider.AddOwner(IResourceHost owner)
   at Avalonia.Styling.Styles.Avalonia.Controls.IResourceProvider.AddOwner(IResourceHost owner)
   at Avalonia.Markup.Xaml.Styling.StyleInclude.Avalonia.Controls.IResourceProvider.AddOwner(IResourceHost owner)
   at Avalonia.Styling.Styles.Avalonia.Controls.IResourceProvider.AddOwner(IResourceHost owner)
   at Avalonia.Markup.Xaml.Styling.StyleInclude.Avalonia.Controls.IResourceProvider.AddOwner(IResourceHost owner)
   at Avalonia.Styling.Styles.<OnCollectionChanged>g__Add|52_1(IList items)
   at Avalonia.Styling.Styles.OnCollectionChanged(Object sender, NotifyCollectionChangedEventArgs e)
   at Avalonia.Collections.AvaloniaList`1.NotifyAdd(T item, Int32 index)
   at Avalonia.Collections.AvaloniaList`1.Add(T item)
   at Avalonia.Styling.Styles.Add(IStyle item)
   at PSX.Avalonia.App.!XamlIlPopulate(IServiceProvider , App ) in C:\Users\aybe\source\repos\ProjectPSX\PSX.Avalonia\App.axaml:line 15
   at PSX.Avalonia.App.!XamlIlPopulateTrampoline(App )
   at PSX.Avalonia.App.Initialize() in C:\Users\aybe\source\repos\ProjectPSX\PSX.Avalonia\App.axaml.cs:line 13
   at Avalonia.Controls.AppBuilderBase`1.Setup()
   at Avalonia.Controls.AppBuilderBase`1.SetupWithLifetime(IApplicationLifetime lifetime)
   at Avalonia.ClassicDesktopStyleApplicationLifetimeExtensions.StartWithClassicDesktopLifetime[T](T builder, String[] args, ShutdownMode shutdownMode)
   at PSX.Avalonia.Program.Main(String[] args) in C:\Users\aybe\source\repos\ProjectPSX\PSX.Avalonia\Program.cs:line 14

  This exception was originally thrown at this call stack:
    [External Code]

Inner Exception 1:
TargetInvocationException: Exception has been thrown by the target of an invocation.

Inner Exception 2:
TypeLoadException: Method 'RunAsync' in type 'Material.Styles.Additional.Animations.ControllableAnimationBase' from assembly 'Material.Styles, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null' does not have an implementation.

```

Any ideas on what's wrong?

**Comment by vector-man** [comment]
Did you ever find a solution? I'm having this issue.

**Comment by aybe** [comment]
Nope, sorry.

**Comment by SKProCH** [comment]
Hello, @vector-man @aybe 

If you want to use `MaterialTheme` you need to install 3.0.0-rc0 version of `Material.Avalonia` (or nightly builds).

As for the `TargetInvocationException`, to use `Material.Avalonia` with the latest versions of Avalonia, you must install at least version 2.5.1 (or higher)
